### ISSUE TITLE
Cleaning up files after FAC packages installation

### ISSUE THREAD

**Issue by pnallin** [lnls-sirius/bbb-daemon#16]
@xresende, could you please remove (rm -rf dist build */*.egg-info *.egg-info) into server folders (10.128.254.203) of machine-applications, dev-packages and mathphys as well?

I didnt succeeded to do so. Thanks!

**Comment by xresende** [comment]
@pnallin , I changed FAC's [deploy script]( https://github.com/lnls-sirius/scripts/blob/master/bin/sirius-script-repos-deploy.bash) to delete temporary installation repo files in the NFS server. (pull request: lnls-sirius/scripts#15)

**Comment by pnallin** [comment]
Thanks!
